# permissions for end users to edit deviceconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deviceconfiguration-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mkoperator
    app.kubernetes.io/part-of: mkoperator
    app.kubernetes.io/managed-by: kustomize
  name: deviceconfiguration-editor-role
rules:
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - deviceconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - deviceconfigurations/status
  verbs:
  - get
