# permissions for end users to view partitiondecisions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: partitiondecision-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mkoperator
    app.kubernetes.io/part-of: mkoperator
    app.kubernetes.io/managed-by: kustomize
  name: partitiondecision-viewer-role
rules:
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - partitiondecisions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - partitiondecisions/status
  verbs:
  - get
