---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - deviceconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - deviceconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - deviceconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - partitiondecisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - partitiondecisions/finalizers
  verbs:
  - update
- apiGroups:
  - devices.devices.dcncompany.com
  resources:
  - partitiondecisions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.kserve.io
  resources:
  - inferencegraphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - inferencegraphs/finalizers
  verbs:
  - update
- apiGroups:
  - serving.kserve.io
  resources:
  - inferencegraphs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices/finalizers
  verbs:
  - update
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices/status
  verbs:
  - get
  - patch
  - update
